# yaml-language-server: $schema=https://raw.githubusercontent.com/rendercv/rendercv/refs/tags/v2.6/schema.json

cv:
  name: Jakub Sarnowski
  location: Gniezno, Poland
  email: hello@jsarnowski.com
  phone: +48 785 748 506
  website: https://jsarnowski.com
  social_networks:
    - network: GitHub
      username: jsardev
    - network: LinkedIn
      username: jsardev
    - network: X
      username: jsardev

  sections:
    Introduction:
      - Experienced engineer passionate about software that is visually appealing, intuitive, fast, and enhances user experience. Known for being a great teammate and collaborator, with a commitment to the team and mission. Possess strong technical skills, coupled with a deep understanding of business needs and goals of the products being developed.

    Experience:
      - company: "[WAYF](https://wayfdigital.com)"
        position: Senior Full-stack Developer
        start_date: 2025-07
        end_date: 2025-10
        location: Remote
        summary: Contributing to development of a large-scale multi-tenant website platform serving 100+ clients.
        highlights:
          - Maintaining and improving website reliability through comprehensive monitoring systems and protocols.
          - Developing caching solutions to enhance performance and optimize hosting costs.

      - company: "[Enixware](https://enixware.com)"
        position: Senior Frontend Developer
        start_date: 2023-11
        end_date: 2025-05
        location: Remote
        summary: Worked on a large-scale web gaming platform serving thousands of concurrent users.
        highlights:
          - Developed an interactive Web3-based browser game and its accompanying landing page.
          - Implemented an automated codebase transformation solution, reducing the development time for a large-scale styling migration from 4 weeks to just 1 week.

      - company: "[Freelancing](https://jsarnowski.com)"
        position: Software Engineer
        start_date: 2023-04
        end_date: 2023-10
        location: Remote
        summary: Worked on a governmental platform for managing citizen-related administrative matters.
        highlights:
          - Created a comprehensive design system library with reusable components, focusing on high accessibility standards following the WCAG guidelines.
          - Developed a landing page featuring complex animations and interactions.

      - company: "[ClickUp](https://clickup.com)"
        position: Senior Frontend Engineer
        start_date: 2022-07
        end_date: 2023-03
        location: Remote
        summary: Worked on a large-scale reactive application, focusing on developing advanced reporting charts and data visualizations.
        highlights:
          - Led initiative to gather data on performance metrics for data visualizations and general user experience.

      - company: "[Netguru](https://netguru.com)"
        position: Senior Frontend Developer
        start_date: 2020-03
        end_date: 2022-06
        location: Remote
        highlights:
          - Engineered a custom server-side rendering solution for an e-commerce platform, improving the Google Lighthouse performance score by 70 points.
          - Built the frontend for a home insurance quoting system with complex calculation logic.
          - Participated in the recruitment process by conducting technical interviews and providing candidates with detailed feedback and growth suggestions.

      - company: ST-YL
        position: React Developer
        start_date: 2019-07
        end_date: 2020-02
        location: Remote
        highlights:
          - Worked on an e-commerce web application in the clothing industry.
          - Enhanced performance by identifying and resolving loading issues, resulting in a 50% improvement in LCP.
          - Implemented search and filtering capabilities, along with advanced analytics.
          - Customized a CMS for the marketing team to easily launch campaigns, integrating it with the storefront for dynamic content.

      - company: "[Freelancing](https://jsarnowski.com)"
        position: Software Engineer
        start_date: 2018-01
        end_date: 2019-06
        location: Remote
        highlights:
          - Developed brand identity and software solutions for a personal trainer, managing the full technology stack and deployment infrastructure.
          - Collaborated closely with the client to ensure software capabilities aligned with the brand's vision.
          - Implemented secure payment processing and a subscription management system.
          - Improved the client's conversion rate by 20% through a custom-coded landing page.

      - company: "[Allegro](https://allegro.pl)"
        position: Software Engineer
        start_date: 2017-04
        end_date: 2017-12
        location: Poznań, Poland
        highlights:
          - Built large-scale applications and microservices in a distributed infrastructure, handling orchestration and DevOps aspects.
          - Engaged in product design and planning, including discussing requirements and creating roadmaps.
          - Collaborated effectively within the team following SCRUM methodology and provided mentorship to junior developers.
          - Maintained and improved outdated systems, optimizing resource usage.

      - company: "[Allegro](https://allegro.pl)"
        position: Junior Software Engineer
        start_date: 2016-01
        end_date: 2017-03
        location: Poznań, Poland
        highlights:
          - Independently worked on a complex application, actively solving problems and engaging in code reviews to enhance learning and independence.
          - Shared knowledge with team members by teaching aspiring Software Engineers and offering test engineering insights.

      - company: "[Allegro](https://allegro.pl)"
        position: Junior QA Engineer
        start_date: 2015-01
        end_date: 2015-12
        location: Poznań, Poland
        highlights:
          - Created automated tests for a microservices-based infrastructure, including multi-browser tests and scheduled jobs for continuous integration.
          - Proposed new technologies to enhance developer experience and worked to improve the company's focus on product quality.
          - Developed clear and replicable bug reports with detailed reproduction steps and prepared test environments.

      - company: "[mTab](https://mtab.com)"
        position: Junior .NET Developer
        start_date: 2015-01
        end_date: 2016-02
        location: Poznań, Poland
        summary: Built an in-house centralized logging platform from scratch to monitor platform usage and improve developer productivity.
        highlights:
          - Designed and developed a comprehensive logging solution using Angular frontend, .NET Web API, and Elasticsearch, enabling real-time monitoring of application logs and errors for hundreds of users.
          - Implemented user activity tracking and error logging capabilities, significantly reducing troubleshooting time and helping developers identify and resolve issues more efficiently.
          - Created a self-hosted monitoring platform as an alternative to Sentry, providing the team with full control over log data and search capabilities.

      - company: "[mTab](https://mtab.com)"
        position: QA Engineer
        start_date: 2013-10
        end_date: 2014-12
        location: Poznań, Poland
        summary: Ensured quality of automotive analytics software through comprehensive manual and automated testing.
        highlights:
          - Validated data accuracy in complex analytics charts and visualizations for automotive sales data, ensuring reliable business intelligence for clients.
          - Developed automated test suites using C# and Selenium for critical user flows, creating documented test cases to support regression testing and prevent data integrity issues.
          - Identified and reported critical bugs through manual testing, tracking all issues in Redmine to maintain high product quality and data reliability.
          - Collaborated with the development team to improve test coverage and testing processes for the analytics platform.

    Skills:
      - label: Languages & Core
        details: TypeScript, JavaScript, Node.js, Java, Kotlin, C#, PHP
      - label: Frontend
        details: React, Next.js, Angular, Astro, Razzle, Redux, Redux Toolkit, RTK Query, Reselect, MobX, Zustand, Recoil, NgRx, Tanstack Query, Tanstack Router, XState, Phaser, Redux Form, React Hook Form
      - label: Backend
        details: Express, Koa, Fastify, Adonis, Spring, Symfony, .NET
      - label: CMS
        details: Sanity, Contentstack, Strapi, Storyblok, Contentful
      - label: Styling & UI
        details: Tailwind, UnoCSS, SCSS, CSS Modules, Storybook, GSAP, React Aria, ShadCN
      - label: Testing
        details: Selenium, Selenium Grid, JMeter, Cypress, Playwright, Gatling, Vegeta, AB
      - label: DevOps, Cloud & Infrastructure
        details: Vercel, Google Cloud, Consul, Mesos, Marathon, GitHub Actions, GitLab Pipelines, Bamboo, GritQL, Hermes, Elasticsearch, Kafka, Redis
      - label: Tools & Utilities
        details: Nx, Ramda, Turbopack, ClickUp, Jira, Confluence, Notion, Trello, Redmine

    Education:
      - institution: Wyższa Szkoła Bankowa
        degree: BS
        area: Software Engineering
        start_date: 2013
        end_date: 2014
        summary: Pursued comprehensive software engineering studies, focusing on the principles of designing, developing, and maintaining efficient software systems. Left the program after one year to gain more practical, hands-on experience by working at a software company.

    Languages:
      - label: Polish
        details: native
      - label: English
        details: advanced
      - label: German
        details: basic

    Non profit:
      - Volunteered at [Devoxx4Kids](https://www.devoxx4kids.org/) to teach programming concepts to children using Scratch, developing interactive workshops and hands-on activities that made coding accessible and fun.

design:
  theme: classic
  page:
    show_footer: true
  colors:
    name: rgb(0, 0, 0)
    section_titles: rgb(0, 0, 0)
  typography:
    font_family: DejaVu Sans Mono
    font_size:
      body: 8pt
  header:
    alignment: left
    connections:
      phone_number_format: international
      hyperlink: true
      show_icons: true
      display_urls_instead_of_usernames: true
      space_between_connections: "0.50cm"
  entries:
    summary:
      space_above: "0.15cm"
    highlights:
      space_above: "0.15cm"
  section_titles:
    type: with_partial_line
    space_above: "0.5cm"
    space_below: "0.5cm"
  links:
    underline: false
    show_external_link_icon: true

locale:
  language: english

rendercv_settings:
  current_date: "2025-12-26"
  render_command:
    pdf_path: rendercv_output/Jakub_Sarnowski_CV.pdf
